# Rede Neural Multicamadas (MPL)
Uma rede MPL é uma classe de rede neural artificial *feedforward* (ANN). Um MLP consiste em pelo menos três camadas de nós: uma camada de entrada , uma camada oculta e uma camada de saída . Exceto para os nós de entrada, cada nó é um neurônio que usa uma função de ativação não linear . O MLP utiliza uma técnica de aprendizado supervisionado chamada *backpropagation* para treinamento.



### Implementando uma RNA multicamadas

A imagem a seguir mostra a nossa rede, com as unidades de entrada marcadas como Input1, Input2 e Input3 (**Input Layer**) conectadas com os *nós* da camada oculta (**Hidden Layer**). Por sua vez as saída dos *nós* da camada oculda servem como entrada para os *nós*  da camada de saída (**Output Layer**). <img src='MPL.png' /><br>

<p style="text-align:center">  <i> Diagrama de uma MPL</i> </p>
 

Lembrando que em cada *nó* temos: 

$$f(h) = sigmoid(h)=\frac 1 {1+e^{-h}}$$  

onde

<p style="text-align:center"> $$h = \frac 1n\sum_{i=1}^n(w_i*x_i)+b$$  </p>




    



## Configuração da MPL

In [1]:
#Importando a biblioteca
import numpy as np

#Função do cáculo da sigmóide
def sigmoid(x):
    return 1/(1+np.exp(-x))

#Arquitetura da MPL
N_input = 3
N_hidden = 4
N_output = 2

#Vetor dos valores de entrada
x = np.array([0.5, 0.1, -0.2])
target =np.array([0.3, 0.8])
learnrate = 0.5

#Pesos da Camada Oculta

weights_input_hidden = np.array([[-0.08,  0.08, -0.03, 0.03],
                              [ 0.05,  0.10,  0.07, 0.02],
                              [-0.07,  0.04, -0.01, 0.01]])

#Pesos da Camada de Saída
weights_hidden_output = np.array([[-0.18,  0.11],
                               [-0.09,  0.05],
                               [-0.04,  0.05],
                               [-0.02,  0.07]])



### Forward Pass

In [2]:
#Camada oculta

#Calcule a combinação linear de entradas e pesos sinápticos
hidden_layer_input = np.dot(x, weights_input_hidden)
#Aplicado a função de ativação
hidden_layer_output = sigmoid(hidden_layer_input)

#Camada de Saída

#Calcule a combinação linear de entradas e pesos sinápticos
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)

#Aplicado a função de ativação 
output = sigmoid(output_layer_in)

print('As saídas da rede são',output)


As saídas da rede são [0.45883963 0.53497652]


## Backward Pass

In [3]:

## TODO: Cálculo do Erro
error = target - output
#print('Erro da Rede: ',error)

# TODO: Calcule o termo de erro de saída (Gradiente da Camada de Saída)
output_error_term = error * output * (1 - output)

# TODO: Calcule a contribuição da camada oculta para o erro
hidden_error = np.dot(weights_hidden_output, output_error_term)

# TODO: Calcule o termo de erro da camada oculta (Gradiente da Camada Oculta)
hidden_error_term = hidden_error * hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calcule a variação do peso da camada de saída
delta_w_h_o = learnrate * output_error_term*hidden_layer_output[:, None]
print('delta_w_h_o: ',delta_w_h_o)

# TODO: Calcule a variação do peso da camada oculta
delta_w_i_h = learnrate * hidden_error_term * x[:, None]
print('delta_w_i_h: ',delta_w_i_h)



delta_w_h_o:  [[-0.00975667  0.01630985]
 [-0.01006724  0.016829  ]
 [-0.00983062  0.01643346]
 [-0.00993415  0.01660653]]
delta_w_i_h:  [[ 8.96890297e-04  4.27702305e-04  3.04635689e-04  3.37732992e-04]
 [ 1.79378059e-04  8.55404611e-05  6.09271378e-05  6.75465983e-05]
 [-3.58756119e-04 -1.71080922e-04 -1.21854276e-04 -1.35093197e-04]]


### Atualização dos Pesos

In [4]:
weights_input_hidden = learnrate * delta_w_i_h
print('weights_input_hidden: ',weights_input_hidden)
weights_hidden_output = learnrate * delta_w_h_o
print('weights_hidden_output: ',weights_hidden_output)

weights_input_hidden:  [[ 4.48445149e-04  2.13851153e-04  1.52317845e-04  1.68866496e-04]
 [ 8.96890297e-05  4.27702305e-05  3.04635689e-05  3.37732992e-05]
 [-1.79378059e-04 -8.55404611e-05 -6.09271378e-05 -6.75465983e-05]]
weights_hidden_output:  [[-0.00487834  0.00815492]
 [-0.00503362  0.0084145 ]
 [-0.00491531  0.00821673]
 [-0.00496708  0.00830327]]
